# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lde-merc <lde-merc@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/07/11 15:57:18 by lde-merc          #+#    #+#              #
#    Updated: 2024/07/11 15:58:26 by lde-merc         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SOURCES = srcs/
CC = cc
FLAGS = -Wall -Wextra -Werror

$(CC) $(FLAGS) -c $(SOURCES)*.c

clean :
	rm -rf $(SOURCES)*.o
fclean :

re :

all :